version: '2.1'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass